### ISSUE TITLE
Scrolling on mobile makes this plugin disappear 

### ISSUE THREAD

**Issue by rbozan** [Aerolab/readremaining.js#1]

**Comment by patopitaluga** [comment]
Hi. Thanks for helping.
It's supposed to disappear when the user is scrolling and appear again when is reading. Maybe it can be set to don't do that on mobile.
What cellphone were you using when you discovered the bug?

**Comment by chinmay185** [comment]
Found the similar disappearing behavior on OnePlus One running Chrome.

**Comment by rbozan** [comment]
I tried it again and yeah it's not bugged, it reappears after a few seconds, however what is bugged is when you scroll to the top. Then it disappears. Just try scrolling casual a bit and then scroll all the way to the top.

**Comment by rbozan** [comment]
(on a LG G2, 4.4.2, Chrome)

**Comment by patopitaluga** [comment]
I tested in Android and iPhone and couldn't replicate the issue. I think I know what it can be: when the estimated time has passed, it considers that the user has finished reading and doesn't show the gauge anymore.
The same thing when the scroll is going up, it considers that the user is not reading so the gauge stops appearing.
I should consider if this feature (or bug) will still be present in the next version. In which case I should document it better.
