### ISSUE TITLE
Detect <video> elements and add them to the count

### ISSUE THREAD

**Issue by tcitworld** [Aerolab/readremaining.js#3]
For instance using this : http://stackoverflow.com/a/2602558

**Comment by patopitaluga** [comment]
That would be great. Maybe it can use a data attribute to set how long the video is, or something similar. I'll think about it. Thanks.

**Comment by tcitworld** [comment]
There's the duration property from any video which should do the trick.

Btw, I'll use readremaining.js for wallabag (we already have such a feature, but I guess it would be better if we use your library).
