### ISSUE TITLE
Would you please uniform the version number in git tag and package.json?

### ISSUE THREAD

**Issue by dannyxx001** [Aerolab/readremaining.js#4]
Hello, I'm a intern from [cdnjs](https://github.com/cdnjs/cdnjs). I want to send pull request to add your library, and it will auto update based on version number in [git tag](https://github.com/Aerolab/readremaining.js/tree/0.1.0). However, the number should be the same in [package.json.](https://github.com/Aerolab/readremaining.js/blob/master/package.json#L3) So would you please uniform the version number in git tag and package.json? Or you call tell me which number I should follow. Thank you.

**Comment by patopitaluga** [comment]
Ok. My bad. I fixed the release version. Thanks

**Comment by dannyxx001** [comment]
OK, Thanks for your collaboration. : )

**Comment by dannyxx001** [comment]
Excuse me, the cdnjs maintainer want me to ask you that would you mind adding a dist folder for distribution files?
cc [7590](https://github.com/cdnjs/cdnjs/pull/7590)

**Comment by dannyxx001** [comment]
@patopitaluga Sorry for bothering you. I just want to make sure you will notify this new issue I mentioned above. Thank you. :)

**Comment by PeterDaveHello** [comment]
@RobertoGonzalez would you mind to take a look? Thanks. cc @sufuf3

**Comment by RobertoGonzalez** [comment]
@PeterDaveHello Hi! Are you referring to the dist folder or tagging a new version? I see there's a few extra commits that didn't get a proper release.

**Comment by PeterDaveHello** [comment]
Hi @RobertoGonzalez, I'm referring the dist folder and it'll be great if we can use the common naming schema, rename the minified file to `readremaining.jquery.min.js` instead of `output.min.js` :)

**Comment by RobertoGonzalez** [comment]
@PeterDaveHello I upped the version to 1.0.1 with those changes. Let me know if it works!

**Comment by PeterDaveHello** [comment]
Awesome! Thanks @RobertoGonzalez

**Comment by sufuf3** [comment]
Thank you very much.
